name: Nadya
favicon: null
layout_spectrum: 0.25732
typography_spectrum: 0.6345168673433363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#57799e'
    - '#bf7c83'
    - '#4c4c4c'
    - '#c7b0c4'
    - '#f8f8fa'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
